import { Country, Region, NewsCategory } from "@/types";

export const CATEGORIES: NewsCategory[] = [
  {
    id: "general",
    name: "General",
    slug: "general",
    description: "Top headlines and general news",
    icon: "newspaper",
  },
  {
    id: "world",
    name: "World",
    slug: "world",
    description: "International news and global affairs",
    icon: "globe",
  },
  {
    id: "politics",
    name: "Politics",
    slug: "politics",
    description: "Political news and government updates",
    icon: "landmark",
  },
  {
    id: "business",
    name: "Business",
    slug: "business",
    description: "Markets, economy, and corporate news",
    icon: "trending-up",
  },
  {
    id: "technology",
    name: "Technology",
    slug: "technology",
    description: "Tech news, gadgets, and innovation",
    icon: "cpu",
  },
  {
    id: "science",
    name: "Science",
    slug: "science",
    description: "Scientific discoveries and research",
    icon: "flask-conical",
  },
  {
    id: "health",
    name: "Health",
    slug: "health",
    description: "Medical news and wellness updates",
    icon: "heart-pulse",
  },
  {
    id: "sports",
    name: "Sports",
    slug: "sports",
    description: "Sports news, scores, and highlights",
    icon: "trophy",
  },
  {
    id: "entertainment",
    name: "Entertainment",
    slug: "entertainment",
    description: "Movies, music, and celebrity news",
    icon: "film",
  },
  {
    id: "environment",
    name: "Environment",
    slug: "environment",
    description: "Climate and environmental news",
    icon: "leaf",
  },
];

export const REGIONS: Region[] = [
  {
    id: "asia",
    name: "Asia",
    slug: "asia",
    countries: [
      "cn",
      "in",
      "jp",
      "kr",
      "id",
      "th",
      "vn",
      "ph",
      "my",
      "sg",
      "bd",
      "pk",
      "lk",
      "np",
      "mm",
    ],
    languages: [
      "en",
      "zh",
      "hi",
      "ja",
      "ko",
      "id",
      "th",
      "vi",
      "ms",
      "bn",
      "ur",
      "ta",
      "te",
    ],
  },
  {
    id: "europe",
    name: "Europe",
    slug: "europe",
    countries: [
      "gb",
      "de",
      "fr",
      "it",
      "es",
      "nl",
      "be",
      "ch",
      "at",
      "se",
      "no",
      "dk",
      "fi",
      "pl",
      "cz",
      "hu",
      "ro",
      "bg",
      "hr",
      "rs",
      "ua",
      "gr",
      "pt",
      "ie",
    ],
    languages: [
      "en",
      "de",
      "fr",
      "it",
      "es",
      "nl",
      "pt",
      "pl",
      "ru",
      "uk",
      "el",
      "cs",
      "hu",
      "ro",
      "sv",
      "da",
      "fi",
      "no",
    ],
  },
  {
    id: "north-america",
    name: "North America",
    slug: "north-america",
    countries: [
      "us",
      "ca",
      "mx",
      "cu",
      "gt",
      "hn",
      "sv",
      "ni",
      "cr",
      "pa",
      "jm",
      "ht",
      "do",
    ],
    languages: ["en", "es", "fr", "ht"],
  },
  {
    id: "south-america",
    name: "South America",
    slug: "south-america",
    countries: [
      "br",
      "ar",
      "cl",
      "co",
      "pe",
      "ve",
      "ec",
      "bo",
      "py",
      "uy",
      "gy",
      "sr",
      "gf",
    ],
    languages: ["pt", "es", "en", "nl", "fr"],
  },
  {
    id: "africa",
    name: "Africa",
    slug: "africa",
    countries: [
      "za",
      "ng",
      "eg",
      "ke",
      "et",
      "tz",
      "ug",
      "rw",
      "gh",
      "ma",
      "dz",
      "tn",
      "ly",
      "sd",
      "ss",
      "cd",
      "ao",
      "mz",
      "zm",
      "zw",
      "bw",
      "na",
      "mg",
      "cm",
      "ci",
      "ml",
      "bf",
      "ne",
      "td",
      "so",
      "er",
      "dj",
      "km",
      "mu",
      "sc",
      "mz",
    ],
    languages: [
      "en",
      "fr",
      "ar",
      "pt",
      "sw",
      "am",
      "ha",
      "yo",
      "ig",
      "zu",
      "af",
      "so",
      "rw",
    ],
  },
  {
    id: "middle-east",
    name: "Middle East",
    slug: "middle-east",
    countries: [
      "sa",
      "ae",
      "qa",
      "kw",
      "bh",
      "om",
      "ye",
      "iq",
      "ir",
      "jo",
      "lb",
      "sy",
      "il",
      "ps",
      "tr",
      "cy",
    ],
    languages: ["ar", "en", "fa", "tr", "he"],
  },
  {
    id: "oceania",
    name: "Oceania",
    slug: "oceania",
    countries: [
      "au",
      "nz",
      "pg",
      "fj",
      "sb",
      "vu",
      "nc",
      "pf",
      "ws",
      "to",
      "ki",
      "tv",
      "nr",
      "fm",
      "mh",
      "pw",
    ],
    languages: ["en", "mi", "sm", "to", "fj", "bi", "tpi"],
  },
];

export const COUNTRIES: Country[] = [
  {
    code: "us",
    name: "United States",
    region: "north-america",
    languages: ["en"],
    flag: "🇺🇸",
  },
  {
    code: "gb",
    name: "United Kingdom",
    region: "europe",
    languages: ["en"],
    flag: "🇬🇧",
  },
  {
    code: "ca",
    name: "Canada",
    region: "north-america",
    languages: ["en", "fr"],
    flag: "🇨🇦",
  },
  {
    code: "au",
    name: "Australia",
    region: "oceania",
    languages: ["en"],
    flag: "🇦🇺",
  },
  {
    code: "in",
    name: "India",
    region: "asia",
    languages: ["en", "hi"],
    flag: "🇮🇳",
  },
  {
    code: "de",
    name: "Germany",
    region: "europe",
    languages: ["de"],
    flag: "🇩🇪",
  },
  {
    code: "fr",
    name: "France",
    region: "europe",
    languages: ["fr"],
    flag: "🇫🇷",
  },
  { code: "jp", name: "Japan", region: "asia", languages: ["ja"], flag: "🇯🇵" },
  { code: "cn", name: "China", region: "asia", languages: ["zh"], flag: "🇨🇳" },
  {
    code: "br",
    name: "Brazil",
    region: "south-america",
    languages: ["pt"],
    flag: "🇧🇷",
  },
  {
    code: "it",
    name: "Italy",
    region: "europe",
    languages: ["it"],
    flag: "🇮🇹",
  },
  {
    code: "es",
    name: "Spain",
    region: "europe",
    languages: ["es"],
    flag: "🇪🇸",
  },
  {
    code: "nl",
    name: "Netherlands",
    region: "europe",
    languages: ["nl"],
    flag: "🇳🇱",
  },
  {
    code: "ru",
    name: "Russia",
    region: "europe",
    languages: ["ru"],
    flag: "🇷🇺",
  },
  {
    code: "za",
    name: "South Africa",
    region: "africa",
    languages: ["en", "af", "zu"],
    flag: "🇿🇦",
  },
  {
    code: "ng",
    name: "Nigeria",
    region: "africa",
    languages: ["en"],
    flag: "🇳🇬",
  },
  {
    code: "eg",
    name: "Egypt",
    region: "africa",
    languages: ["ar"],
    flag: "🇪🇬",
  },
  {
    code: "ke",
    name: "Kenya",
    region: "africa",
    languages: ["en", "sw"],
    flag: "🇰🇪",
  },
  {
    code: "sa",
    name: "Saudi Arabia",
    region: "middle-east",
    languages: ["ar"],
    flag: "🇸🇦",
  },
  {
    code: "ae",
    name: "UAE",
    region: "middle-east",
    languages: ["ar", "en"],
    flag: "🇦🇪",
  },
  {
    code: "kr",
    name: "South Korea",
    region: "asia",
    languages: ["ko"],
    flag: "🇰🇷",
  },
  {
    code: "id",
    name: "Indonesia",
    region: "asia",
    languages: ["id"],
    flag: "🇮🇩",
  },
  {
    code: "mx",
    name: "Mexico",
    region: "north-america",
    languages: ["es"],
    flag: "🇲🇽",
  },
  {
    code: "ar",
    name: "Argentina",
    region: "south-america",
    languages: ["es"],
    flag: "🇦🇷",
  },
  {
    code: "tr",
    name: "Turkey",
    region: "europe",
    languages: ["tr"],
    flag: "🇹🇷",
  },
  {
    code: "se",
    name: "Sweden",
    region: "europe",
    languages: ["sv"],
    flag: "🇸🇪",
  },
  {
    code: "no",
    name: "Norway",
    region: "europe",
    languages: ["no"],
    flag: "🇳🇴",
  },
  {
    code: "pl",
    name: "Poland",
    region: "europe",
    languages: ["pl"],
    flag: "🇵🇱",
  },
  {
    code: "be",
    name: "Belgium",
    region: "europe",
    languages: ["nl", "fr", "de"],
    flag: "🇧🇪",
  },
  {
    code: "ch",
    name: "Switzerland",
    region: "europe",
    languages: ["de", "fr", "it"],
    flag: "🇨🇭",
  },
  {
    code: "at",
    name: "Austria",
    region: "europe",
    languages: ["de"],
    flag: "🇦🇹",
  },
  {
    code: "gr",
    name: "Greece",
    region: "europe",
    languages: ["el"],
    flag: "🇬🇷",
  },
  {
    code: "pt",
    name: "Portugal",
    region: "europe",
    languages: ["pt"],
    flag: "🇵🇹",
  },
  {
    code: "dk",
    name: "Denmark",
    region: "europe",
    languages: ["da"],
    flag: "🇩🇰",
  },
  {
    code: "fi",
    name: "Finland",
    region: "europe",
    languages: ["fi", "sv"],
    flag: "🇫🇮",
  },
  {
    code: "ie",
    name: "Ireland",
    region: "europe",
    languages: ["en", "ga"],
    flag: "🇮🇪",
  },
  {
    code: "nz",
    name: "New Zealand",
    region: "oceania",
    languages: ["en", "mi"],
    flag: "🇳🇿",
  },
  {
    code: "sg",
    name: "Singapore",
    region: "asia",
    languages: ["en", "zh", "ms", "ta"],
    flag: "🇸🇬",
  },
  {
    code: "my",
    name: "Malaysia",
    region: "asia",
    languages: ["ms", "en", "zh", "ta"],
    flag: "🇲🇾",
  },
  {
    code: "th",
    name: "Thailand",
    region: "asia",
    languages: ["th"],
    flag: "🇹🇭",
  },
  {
    code: "vn",
    name: "Vietnam",
    region: "asia",
    languages: ["vi"],
    flag: "🇻🇳",
  },
  {
    code: "ph",
    name: "Philippines",
    region: "asia",
    languages: ["en", "tl"],
    flag: "🇵🇭",
  },
  {
    code: "pk",
    name: "Pakistan",
    region: "asia",
    languages: ["en", "ur"],
    flag: "🇵🇰",
  },
  {
    code: "bd",
    name: "Bangladesh",
    region: "asia",
    languages: ["bn"],
    flag: "🇧🇩",
  },
  {
    code: "lk",
    name: "Sri Lanka",
    region: "asia",
    languages: ["si", "ta"],
    flag: "🇱🇰",
  },
  { code: "np", name: "Nepal", region: "asia", languages: ["ne"], flag: "🇳🇵" },
  {
    code: "cl",
    name: "Chile",
    region: "south-america",
    languages: ["es"],
    flag: "🇨🇱",
  },
  {
    code: "co",
    name: "Colombia",
    region: "south-america",
    languages: ["es"],
    flag: "🇨🇴",
  },
  {
    code: "pe",
    name: "Peru",
    region: "south-america",
    languages: ["es"],
    flag: "🇵🇪",
  },
  {
    code: "ve",
    name: "Venezuela",
    region: "south-america",
    languages: ["es"],
    flag: "🇻🇪",
  },
  {
    code: "ec",
    name: "Ecuador",
    region: "south-america",
    languages: ["es"],
    flag: "🇪🇨",
  },
  {
    code: "uy",
    name: "Uruguay",
    region: "south-america",
    languages: ["es"],
    flag: "🇺🇾",
  },
  {
    code: "cu",
    name: "Cuba",
    region: "north-america",
    languages: ["es"],
    flag: "🇨🇺",
  },
  {
    code: "il",
    name: "Israel",
    region: "middle-east",
    languages: ["he", "ar"],
    flag: "🇮🇱",
  },
  {
    code: "jo",
    name: "Jordan",
    region: "middle-east",
    languages: ["ar"],
    flag: "🇯🇴",
  },
  {
    code: "lb",
    name: "Lebanon",
    region: "middle-east",
    languages: ["ar"],
    flag: "🇱🇧",
  },
  {
    code: "qa",
    name: "Qatar",
    region: "middle-east",
    languages: ["ar"],
    flag: "🇶🇦",
  },
  {
    code: "kw",
    name: "Kuwait",
    region: "middle-east",
    languages: ["ar"],
    flag: "🇰🇼",
  },
  {
    code: "bh",
    name: "Bahrain",
    region: "middle-east",
    languages: ["ar"],
    flag: "🇧🇭",
  },
  {
    code: "om",
    name: "Oman",
    region: "middle-east",
    languages: ["ar"],
    flag: "🇴🇲",
  },
  {
    code: "et",
    name: "Ethiopia",
    region: "africa",
    languages: ["am", "en", "om"],
    flag: "🇪🇹",
  },
  {
    code: "tz",
    name: "Tanzania",
    region: "africa",
    languages: ["sw", "en"],
    flag: "🇹🇿",
  },
  {
    code: "ug",
    name: "Uganda",
    region: "africa",
    languages: ["en", "sw"],
    flag: "🇺🇬",
  },
  {
    code: "gh",
    name: "Ghana",
    region: "africa",
    languages: ["en"],
    flag: "🇬🇭",
  },
  {
    code: "ma",
    name: "Morocco",
    region: "africa",
    languages: ["ar"],
    flag: "🇲🇦",
  },
  {
    code: "dz",
    name: "Algeria",
    region: "africa",
    languages: ["ar"],
    flag: "🇩🇿",
  },
  {
    code: "tn",
    name: "Tunisia",
    region: "africa",
    languages: ["ar"],
    flag: "🇹🇳",
  },
  {
    code: "cz",
    name: "Czech Republic",
    region: "europe",
    languages: ["cs"],
    flag: "🇨🇿",
  },
  {
    code: "hu",
    name: "Hungary",
    region: "europe",
    languages: ["hu"],
    flag: "🇭🇺",
  },
  {
    code: "ro",
    name: "Romania",
    region: "europe",
    languages: ["ro"],
    flag: "🇷🇴",
  },
  {
    code: "bg",
    name: "Bulgaria",
    region: "europe",
    languages: ["bg"],
    flag: "🇧🇬",
  },
  {
    code: "hr",
    name: "Croatia",
    region: "europe",
    languages: ["hr"],
    flag: "🇭🇷",
  },
  {
    code: "rs",
    name: "Serbia",
    region: "europe",
    languages: ["sr"],
    flag: "🇷🇸",
  },
  {
    code: "ua",
    name: "Ukraine",
    region: "europe",
    languages: ["uk"],
    flag: "🇺🇦",
  },
];

export const LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "bg", name: "Bulgarian", nativeName: "Български" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
];

export const NEWS_SOURCES = {
  apis: {
    newsapi: {
      name: "NewsAPI",
      url: "https://newsapi.org",
      categories: [
        "general",
        "business",
        "technology",
        "entertainment",
        "sports",
        "science",
        "health",
      ],
      countries: [
        "us",
        "gb",
        "ca",
        "au",
        "in",
        "de",
        "fr",
        "it",
        "ru",
        "sa",
        "ae",
        "ar",
        "br",
        "cn",
        "hk",
        "id",
        "il",
        "jp",
        "kr",
        "mx",
        "my",
        "ng",
        "nl",
        "no",
        "nz",
        "ph",
        "pl",
        "sg",
        "tw",
        "th",
        "tr",
        "ua",
        "ve",
        "za",
      ],
    },
    gnews: {
      name: "GNews",
      url: "https://gnews.io",
      categories: [
        "general",
        "world",
        "nation",
        "business",
        "technology",
        "entertainment",
        "sports",
        "science",
        "health",
      ],
      countries: [
        "us",
        "gb",
        "ca",
        "au",
        "in",
        "de",
        "fr",
        "it",
        "ru",
        "sa",
        "ae",
        "ar",
        "br",
        "cn",
        "hk",
        "id",
        "il",
        "jp",
        "kr",
        "mx",
        "my",
        "ng",
        "nl",
        "no",
        "nz",
        "ph",
        "pl",
        "sg",
        "tw",
        "th",
        "tr",
        "ua",
        "ve",
        "za",
      ],
    },
    currents: {
      name: "Currents API",
      url: "https://api.currentsapi.services",
      categories: [
        "general",
        "business",
        "technology",
        "entertainment",
        "sports",
        "science",
        "health",
        "politics",
      ],
    },
  },
  rss: {
    asahi: {
      name: "Asahi Shimbun",
      url: "https://www.asahi.com/english/rss/",
      country: "jp",
      language: "en",
      category: "general",
    },
    kyodo: {
      name: "Kyodo News",
      url: "https://english.kyodonews.net/rss/news.xml",
      country: "jp",
      language: "en",
      category: "general",
    },
    "the-hindu": {
      name: "The Hindu",
      url: "https://www.thehindu.com/news/?service=rss",
      country: "in",
      language: "en",
      category: "general",
    },
    "times-of-india": {
      name: "Times of India",
      url: "https://timesofindia.indiatimes.com/rssfeeds/1898055.cms",
      country: "in",
      language: "en",
      category: "general",
    },
    cna: {
      name: "Channel News Asia",
      url: "https://www.channelnewsasia.com/rssfeeds/8395986",
      country: "sg",
      language: "en",
      category: "general",
    },
    "straits-times": {
      name: "Straits Times",
      url: "https://www.straitstimes.com/news/singapore/rss.xml",
      country: "sg",
      language: "en",
      category: "general",
    },
    jakartapost: {
      name: "Jakarta Post",
      url: "https://www.thejakartapost.com/rss",
      country: "id",
      language: "en",
      category: "general",
    },
    "bangkok-post": {
      name: "Bangkok Post",
      url: "https://www.bangkokpost.com/rss/data/topstories.xml",
      country: "th",
      language: "en",
      category: "general",
    },
    scmp: {
      name: "South China Morning Post",
      url: "https://www.scmp.com/rss/91/feed",
      country: "hk",
      language: "en",
      category: "general",
    },
    "global-times": {
      name: "Global Times",
      url: "https://www.globaltimes.cn/rss/index.xml",
      country: "cn",
      language: "en",
      category: "general",
    },
    "korea-herald": {
      name: "Korea Herald",
      url: "http://www.koreaherald.com/rss/05010000.xml",
      country: "kr",
      language: "en",
      category: "general",
    },
    "korea-times": {
      name: "Korea Times",
      url: "http://www.koreatimes.co.kr/www/rss/nation.xml",
      country: "kr",
      language: "en",
      category: "general",
    },
    dawn: {
      name: "Dawn",
      url: "https://www.dawn.com/feeds/home",
      country: "pk",
      language: "en",
      category: "general",
    },
    "daily-star": {
      name: "Daily Star",
      url: "https://www.thedailystar.net/rss.xml",
      country: "bd",
      language: "en",
      category: "general",
    },
    "manila-bulletin": {
      name: "Manila Bulletin",
      url: "https://mb.com.ph/rss",
      country: "ph",
      language: "en",
      category: "general",
    },
    bbc: {
      name: "BBC News",
      url: "http://feeds.bbci.co.uk/news/rss.xml",
      country: "gb",
      language: "en",
      category: "general",
    },
    guardian: {
      name: "The Guardian",
      url: "https://www.theguardian.com/world/rss",
      country: "gb",
      language: "en",
      category: "general",
    },
    reuters: {
      name: "Reuters",
      url: "https://www.reutersagency.com/feed/?taxonomy=markets&post_type=reuters-best",
      country: "gb",
      language: "en",
      category: "general",
    },
    france24: {
      name: "France 24",
      url: "https://www.france24.com/en/rss",
      country: "fr",
      language: "en",
      category: "general",
    },
    spiegel: {
      name: "Spiegel",
      url: "https://www.spiegel.de/international/index.rss",
      country: "de",
      language: "en",
      category: "general",
    },
    dw: {
      name: "Deutsche Welle",
      url: "https://rss.dw.com/rdf/rss-en-all",
      country: "de",
      language: "en",
      category: "general",
    },
    "the-local-fr": {
      name: "The Local France",
      url: "https://www.thelocal.fr/feeds/rss.php",
      country: "fr",
      language: "en",
      category: "general",
    },
    "the-local-de": {
      name: "The Local Germany",
      url: "https://www.thelocal.de/feeds/rss.php",
      country: "de",
      language: "en",
      category: "general",
    },
    "politico-eu": {
      name: "Politico EU",
      url: "https://www.politico.eu/feed/",
      country: "gb",
      language: "en",
      category: "politics",
    },
    euronews: {
      name: "Euronews",
      url: "https://www.euronews.com/rss",
      country: "gb",
      language: "en",
      category: "general",
    },
    "moscow-times": {
      name: "Moscow Times",
      url: "https://www.themoscowtimes.com/rss/news",
      country: "ru",
      language: "en",
      category: "general",
    },
    rferl: {
      name: "Radio Free Europe",
      url: "https://www.rferl.org/api/",
      country: "us",
      language: "en",
      category: "general",
    },
    swissinfo: {
      name: "Swissinfo",
      url: "https://www.swissinfo.ch/eng/rss",
      country: "ch",
      language: "en",
      category: "general",
    },
    dutchnews: {
      name: "Dutch News",
      url: "https://www.dutchnews.nl/feed/",
      country: "nl",
      language: "en",
      category: "general",
    },
    "irish-times": {
      name: "Irish Times",
      url: "https://www.irishtimes.com/rss/news",
      country: "ie",
      language: "en",
      category: "general",
    },
    "al-jazeera": {
      name: "Al Jazeera",
      url: "https://www.aljazeera.com/xml/rss/all.xml",
      country: "qa",
      language: "en",
      category: "general",
    },
    "jordan-times": {
      name: "Jordan Times",
      url: "https://www.jordantimes.com/rss",
      country: "jo",
      language: "en",
      category: "general",
    },
    "daily-sabah": {
      name: "Daily Sabah",
      url: "https://www.dailysabah.com/rss",
      country: "tr",
      language: "en",
      category: "general",
    },
    hurriyet: {
      name: "Hurriyet Daily",
      url: "https://www.hurriyetdailynews.com/rss",
      country: "tr",
      language: "en",
      category: "general",
    },
    "jerusalem-post": {
      name: "Jerusalem Post",
      url: "https://www.jpost.com/Rss/RssFeedsHeadlines.aspx",
      country: "il",
      language: "en",
      category: "general",
    },
    "times-of-israel": {
      name: "Times of Israel",
      url: "https://www.timesofisrael.com/feed/",
      country: "il",
      language: "en",
      category: "general",
    },
    "egypt-today": {
      name: "Egypt Today",
      url: "https://www.egypttoday.com/rss",
      country: "eg",
      language: "en",
      category: "general",
    },
    "gulf-news": {
      name: "Gulf News",
      url: "https://gulfnews.com/rss",
      country: "ae",
      language: "en",
      category: "general",
    },
    "khaleej-times": {
      name: "Khaleej Times",
      url: "https://www.khaleejtimes.com/feed",
      country: "ae",
      language: "en",
      category: "general",
    },
    "arab-news": {
      name: "Arab News",
      url: "https://www.arabnews.com/rss.xml",
      country: "sa",
      language: "en",
      category: "general",
    },
    "mail-guardian": {
      name: "Mail & Guardian",
      url: "https://mg.co.za/feed/",
      country: "za",
      language: "en",
      category: "general",
    },
    "premium-times": {
      name: "Premium Times",
      url: "https://www.premiumtimesng.com/feed",
      country: "ng",
      language: "en",
      category: "general",
    },
    "nation-kenya": {
      name: "Daily Nation",
      url: "https://nation.africa/kenya/rss",
      country: "ke",
      language: "en",
      category: "general",
    },
    "the-east-african": {
      name: "The East African",
      url: "https://www.theeastafrican.co.ke/rss",
      country: "ke",
      language: "en",
      category: "general",
    },
    allafrica: {
      name: "AllAfrica",
      url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
      country: "za",
      language: "en",
      category: "general",
    },
    "egypt-independent": {
      name: "Egypt Independent",
      url: "https://www.egyptindependent.com/feed/",
      country: "eg",
      language: "en",
      category: "general",
    },
    "ethiopian-reporter": {
      name: "Ethiopian Reporter",
      url: "https://www.ethiopianreporter.com/feed",
      country: "et",
      language: "en",
      category: "general",
    },
    nyt: {
      name: "New York Times",
      url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
      country: "us",
      language: "en",
      category: "general",
    },
    "washington-post": {
      name: "Washington Post",
      url: "https://www.washingtonpost.com/world/rss",
      country: "us",
      language: "en",
      category: "general",
    },
    cnn: {
      name: "CNN",
      url: "http://rss.cnn.com/rss/edition_world.rss",
      country: "us",
      language: "en",
      category: "general",
    },
    npr: {
      name: "NPR",
      url: "https://feeds.npr.org/1001/rss.xml",
      country: "us",
      language: "en",
      category: "general",
    },
    ap: {
      name: "Associated Press",
      url: "https://rsshub.app/apnews/topics/apf-topnews",
      country: "us",
      language: "en",
      category: "general",
    },
    cbc: {
      name: "CBC News",
      url: "https://www.cbc.ca/cmlink/rss-world",
      country: "ca",
      language: "en",
      category: "general",
    },
    "globe-mail": {
      name: "Globe and Mail",
      url: "https://www.theglobeandmail.com/rss",
      country: "ca",
      language: "en",
      category: "general",
    },
    folha: {
      name: "Folha de S.Paulo",
      url: "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
      country: "br",
      language: "pt",
      category: "general",
    },
    globo: {
      name: "Globo",
      url: "https://g1.globo.com/rss/g1/",
      country: "br",
      language: "pt",
      category: "general",
    },
    clarin: {
      name: "Clarin",
      url: "https://www.clarin.com/rss/lo-ultimo/",
      country: "ar",
      language: "es",
      category: "general",
    },
    lanacion: {
      name: "La Nacion",
      url: "https://www.lanacion.com.ar/rss/",
      country: "ar",
      language: "es",
      category: "general",
    },
    reforma: {
      name: "Reforma",
      url: "https://www.reforma.com/rss/",
      country: "mx",
      language: "es",
      category: "general",
    },
    "el-universal-mx": {
      name: "El Universal",
      url: "https://www.eluniversal.com.mx/rss",
      country: "mx",
      language: "es",
      category: "general",
    },
    "abc-au": {
      name: "ABC News Australia",
      url: "https://www.abc.net.au/news/feed/2942460/rss.xml",
      country: "au",
      language: "en",
      category: "general",
    },
    "sydney-morning-herald": {
      name: "Sydney Morning Herald",
      url: "https://www.smh.com.au/rss/feed.xml",
      country: "au",
      language: "en",
      category: "general",
    },
    "nz-herald": {
      name: "NZ Herald",
      url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/1/",
      country: "nz",
      language: "en",
      category: "general",
    },
    stuff: {
      name: "Stuff",
      url: "https://www.stuff.co.nz/rss",
      country: "nz",
      language: "en",
      category: "general",
    },
    techcrunch: {
      name: "TechCrunch",
      url: "https://techcrunch.com/feed/",
      country: "us",
      language: "en",
      category: "technology",
    },
    "the-verge": {
      name: "The Verge",
      url: "https://www.theverge.com/rss/index.xml",
      country: "us",
      language: "en",
      category: "technology",
    },
    wired: {
      name: "Wired",
      url: "https://www.wired.com/feed/rss",
      country: "us",
      language: "en",
      category: "technology",
    },
    "ars-technica": {
      name: "Ars Technica",
      url: "https://arstechnica.com/feed/",
      country: "us",
      language: "en",
      category: "technology",
    },
    "rest-of-world": {
      name: "Rest of World",
      url: "https://restofworld.org/feed/",
      country: "us",
      language: "en",
      category: "technology",
    },
    "financial-times": {
      name: "Financial Times",
      url: "https://www.ft.com/?format=rss",
      country: "gb",
      language: "en",
      category: "business",
    },
    economist: {
      name: "The Economist",
      url: "https://www.economist.com/latest/rss.xml",
      country: "gb",
      language: "en",
      category: "business",
    },
    wsj: {
      name: "Wall Street Journal",
      url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
      country: "us",
      language: "en",
      category: "business",
    },
    bloomberg: {
      name: "Bloomberg",
      url: "https://feeds.bloomberg.com/news.rss",
      country: "us",
      language: "en",
      category: "business",
    },
    forbes: {
      name: "Forbes",
      url: "https://www.forbes.com/real-time/feed/",
      country: "us",
      language: "en",
      category: "business",
    },
    "business-insider": {
      name: "Business Insider",
      url: "https://www.businessinsider.com/rss",
      country: "us",
      language: "en",
      category: "business",
    },
    "economist-es": {
      name: "Economist en Español",
      url: "https://economiaenespanol.economist.com/feed/",
      country: "gb",
      language: "es",
      category: "business",
    },
    "global-voices": {
      name: "Global Voices",
      url: "https://globalvoices.org/feed/",
      country: "us",
      language: "en",
      category: "general",
    },
    mongabay: {
      name: "Mongabay",
      url: "https://news.mongabay.com/feed/",
      country: "us",
      language: "en",
      category: "environment",
    },
    "carbon-brief": {
      name: "Carbon Brief",
      url: "https://www.carbonbrief.org/feed/",
      country: "gb",
      language: "en",
      category: "environment",
    },
    devex: {
      name: "Devex",
      url: "https://www.devex.com/rss",
      country: "us",
      language: "en",
      category: "general",
    },
  },
};

export const API_KEYS = {
  NEWSAPI: process.env.NEWSAPI_KEY || "demo",
  GNEWS: process.env.GNEWS_KEY || "demo",
  CURRENTS: process.env.CURRENTS_KEY || "demo",
};
